<Project Sdk="Aspire.AppHost.Sdk/13.5.4">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>4299efbf-edf0-4462-b914-00b7f2501461</UserSecretsId>
    <AspireUseCliBundle>true</AspireUseCliBundle>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArquitecturaBase.Api\ArquitecturaBase.Api.csproj" />
  </ItemGroup>
</Project>
