<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Los .resx sin sufijo están en español. -->
    <NeutralLanguage>es</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArquitecturaBase.Domain\ArquitecturaBase.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ArquitecturaBase.Application.UnitTests" />
  </ItemGroup>
</Project>
