<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\ArquitecturaBase.Application\ArquitecturaBase.Application.csproj" />
    <ProjectReference Include="..\ArquitecturaBase.Infrastructure\ArquitecturaBase.Infrastructure.csproj" />
    <ProjectReference Include="..\ArquitecturaBase.ServiceDefaults\ArquitecturaBase.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ArquitecturaBase.Api.IntegrationTests" />
  </ItemGroup>
</Project>
